#!/bin/bash

set -e

{    
    set -x
    
    destination=$1
    cd $destination

    TMPDIR=${TMPDIR:-/tmp}
    payload=$(mktemp $TMPDIR/concourse-flyway-resource.XXXXXX)
    cat > $payload <&0
    

    params=$(jq -r '.params // ""' < $payload)
    source=$(jq -r '.source // ""' < $payload)

    migrate=$(echo $params | jq -r '.migrate // false')
    repair=$(echo $params | jq -r '.repair // false')
    migrations_dir=$(echo $params | jq -r '.migrations_dir // ""')

    if [ $migrate = "false" ] && [ $repair = "false" ]; then
        echo "invalid params (either migrate or repair must be true):" >&2
        cat $params >&2
        exit 1
    fi

    db_url=$(echo $source | jq -r '.db_url // ""')
    db_user=$(echo $source | jq -r '.db_user // ""')
    db_password=$(echo $source | jq -r '.db_password // ""')    

    if [ $migrate = "true" ]; then
        flyway migrate -url="$db_url"  \
                      -user="$db_user" \
                      -password="$db_password" \
                      -locations="filesystem:$migrations_dir" \
                      -X
    fi
} >&2

jq -n '{"version": { "ref": "'`date +"%m-%d-%Y_%H-%M-%S"`'"} }'